##
## EPITECH PROJECT, 2024
## Rush 1
## File description:
## Makefile
##

SRC    =    Main.hs

NAME    =    pushswap_checker

all:    $(NAME)

$(NAME):
	ghc -o $(NAME) $(SRC)

clean:
	rm -f *.o
	rm -f *.hi

fclean:    clean
	rm -f $(NAME)

re:    fclean all
