#!/usr/bin/env python3

from parsing import get_parsing


def f_x(exp, x):
    if len(exp) == 1:
        return exp[0]
    else:
        return exp[0] + x * f_x(exp[1:], x)


exp_array = get_parsing()

x = 0
step = 0.001

while x <= 1 + step:
    result = 1
    for i in range(0, len(exp_array), 2):
        num = f_x(exp_array[i], x)
        den = f_x(exp_array[i + 1], x)
        if den == 0:
            exit(84)
        result *= (num / den)
    print("{:.3f} -> {:.5f}".format(x, result))
    x += step
