#!/usr/bin/env python3

##
## EPITECH PROJECT, 2024
## 201yams
## File description:
## 201yams.py
##

from parsing import parsing
from combinations import simulate_pair, simulate_three, simulate_four, simulate_full, simulate_straight, simulate_yams

cases = [("pair", simulate_pair),
         ("three", simulate_three),
         ("four", simulate_four),
         ("full", simulate_full),
         ("straight", simulate_straight),
         ("yams", simulate_yams)]

values, combination_name, combination_number, sec_combination_number = parsing()

if combination_number < 1 or combination_number > 6:
    exit(84)
if sec_combination_number is not None and (sec_combination_number < 1 or sec_combination_number > 6):
    exit(84)
if combination_number == sec_combination_number:
    exit(84)

found_combination = [item for item in cases if combination_name == item[0]]
if len(found_combination) == 0:
    exit(84)

print(found_combination[0][1](values, combination_number, sec_combination_number))
