#!/usr/bin/env python3

##
## EPITECH PROJECT, 2022
## B-MAT-100-STG-1-1-103cipher-florent.guittre
## File description:
## 103cipher
##

import parsing
import work

message, key, flag = parsing.get_arguments()

if (flag == 0):
    work.encrypt(message, key)
if (flag == 1):
    work.decrypt(message, key)
