##
## EPITECH PROJECT, 2024
## Paradigms Seminar
## File description:
## Day02
##

SRC	=	DoOp.hs

NAME	=	doop

all:
	ghc -o $(NAME) $(SRC)

clean:
	rm -f *.o
	rm -f *.hi

fclean:	clean
	rm -f $(NAME)

re:	fclean all
