- name: "Upload poll"
  unarchive:
    src: ./poll.tar
    dest: /opt

- name: 'Install Python'
  apt:
    name: python3, python3-venv, python3-setuptools, python3-pip
    state: present

- name: "Create virtual environment"
  shell: python3 -m venv /opt/poll/venv
  args:
    creates: /opt/poll/venv

- name: "Install dependencies"
  shell: /opt/poll/venv/bin/pip install -r /opt/poll/requirements.txt

- name: "Copy run script file"
  copy:
    src: ../files/run.sh
    dest: /opt/poll
    mode: 0777
    owner: poll

- name: "Copy service file"
  copy:
    src: ../files/poll.service
    dest: /etc/systemd/system/poll.service
    mode: 0644
    owner: poll

- name: "Restart poll"
  service:
    name: poll.service
    state: restarted
